name: Build Qt

on: [ push, pull_request ]

jobs:
  build_linux:
    name: Static Qt for Linux
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    steps:
    - name: Install dependencies for Linux
      run: |
        sed -i '/deb-src/s/^#//g' /etc/apt/sources.list
        apt-get -qq update
        apt-get build-dep -y -qq qt5-default
        apt-get install -y -qq libxcb-xinerama0-dev git zip perl cmake
        apt-get install -y -qq '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev \
          libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
    - name: Checkout for Linux
      uses: actions/checkout@v1
    - name: Build for Linux
      run: chmod +x ./build_linux.sh; ./build_linux.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux
        path: /*.zip
  build_macos:
    name: Static Qt for macOS
    runs-on: macos-latest
    steps:
    - name: Checkout for macOS
      uses: actions/checkout@v1
    - name: Build for macOS
      run: chmod +x ./build_macos.sh; ./build_macos.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: macos
        path: qt5/build/*.zip
